### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by troypdx**
- Modified Riley's original `backend` branch to use a PostgreSQL database rather than sqlite3 (settings.py)
- Added a SQL script that defines database (housing), user (housingdatauser), role and privileges
- Updated README

### CODE REVIEW

**Comment by JohnTasto** [comment]
We don't need that psql script - the Postgres Docker image already has a default user.

**Comment by JohnTasto** [comment]
We should really use environment variables in the settings.py file so we can easily change them when going from dev to staging to production. In dev, the default user in the Postgres Docker image is fine.

**Comment by ericalmadovapsu** [comment]
I agree with John. Plus we never want any credentials on github.

**Comment by JohnTasto** [comment]
Just submitted a different PR that Dockerizes and automates almost all of the setup: https://github.com/hackoregon/housing-17/pull/27

It also uses PostgreSQL.

I had to completely rewrite the readme, but I pulled the intro off of this PR. I suggest closing this PR because the one I just submitted covers everything this one does, plus Docker.

**Comment by troypdx** [comment]
Getting out of the way of John...

**Pull request closed without merging**
